spring.application.name=react_subject_back

#server port
server.port=8989

#oracle 
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=react_subject
spring.datasource.password=1234

#mybatis 
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
mybatis.configuration.jdbc-type-for-null=NULL

#jwt
#jwt.secret-key=kh.web.secret.code.long.long.long.aaaa.bbb.ccc
jwt.secret-key=6kYz6Fh2Vb5yWlJ3d2hVdHhYc1p6aVh3T2pYb1JqZ3l3Rk5lR3Z5Y2pGZk5wR2V2c1pJd3lQZk5yY3ZtWlVxQ0p2d0p3c1RrV2h6eA==
jwt.expire-hour=1